function LoaderOne() {
  return (
    <>
      <svg
        width="1452"
        height="1043"
        viewBox="0 0 1452 1043"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g id="loaderOne">
          <rect
            id="Location"
            x="180"
            y="190"
            width="404"
            height="97"
            rx="4"
            fill="#E5E5E5"
          />
          <rect
            id="Time"
            x="180"
            y="442"
            width="395"
            height="29"
            rx="4"
            fill="#E5E5E5"
          />
          <rect
            id="DayNightRect"
            x="832"
            y="210"
            width="171"
            height="66"
            rx="4"
            fill="#E5E5E5"
          />
          <rect
            id="WeatherTypeRect"
            x="1048"
            y="210"
            width="171"
            height="66"
            rx="4"
            fill="#E5E5E5"
          />
          <g id="ForecastCard3">
            <g id="Card" filter="url(#filter0_b_25_6344)">
              <rect
                x="796"
                y="478"
                width="132"
                height="190"
                rx="4"
                fill="#3B4856"
                fillOpacity="0.3"
              />
            </g>
            <rect
              id="BottomRect"
              x="826"
              y="613"
              width="72"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="Icon"
              x="839"
              y="553"
              width="46"
              height="43"
              rx="21.5"
              fill="#E5E5E5"
            />
            <rect
              id="TopRect"
              x="826"
              y="505"
              width="72"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
          </g>
          <g id="ForecastCard2">
            <g id="Card_2" filter="url(#filter1_b_25_6344)">
              <rect
                x="957"
                y="478"
                width="132"
                height="190"
                rx="4"
                fill="#3B4856"
                fillOpacity="0.3"
              />
            </g>
            <rect
              id="BottomRect_2"
              x="987"
              y="613"
              width="72"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="Icon_2"
              x="1000"
              y="553"
              width="46"
              height="43"
              rx="21.5"
              fill="#E5E5E5"
            />
            <rect
              id="TopRect_2"
              x="987"
              y="505"
              width="72"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
          </g>
          <g id="ForecastCard1">
            <g id="Card_3" filter="url(#filter2_b_25_6344)">
              <rect
                x="1119"
                y="478"
                width="132"
                height="190"
                rx="4"
                fill="#3B4856"
                fillOpacity="0.3"
              />
            </g>
            <rect
              id="BottomRect_3"
              x="1149"
              y="613"
              width="72"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="Icon_3"
              x="1162"
              y="553"
              width="46"
              height="43"
              rx="21.5"
              fill="#E5E5E5"
            />
            <rect
              id="TopRect_3"
              x="1149"
              y="505"
              width="72"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
          </g>
          <g id="MainCardGroup">
            <g id="Card_4" filter="url(#filter3_b_25_6344)">
              <rect
                x="180"
                y="478"
                width="395"
                height="422"
                rx="8"
                fill="#3B4856"
                fillOpacity="0.3"
              />
            </g>
            <rect
              id="Temp"
              x="257"
              y="522"
              width="241"
              height="147"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="Icon_4"
              x="424"
              y="689"
              width="46"
              height="43"
              rx="21.5"
              fill="#E5E5E5"
            />
            <rect
              id="WeatherType"
              x="284"
              y="690"
              width="131"
              height="41"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="BottomRect1"
              x="234"
              y="799"
              width="111"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="BottomRect2"
              x="412"
              y="799"
              width="111"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="BottomRect3"
              x="234"
              y="837"
              width="111"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
            <rect
              id="BottomRect4"
              x="412"
              y="837"
              width="111"
              height="28"
              rx="4"
              fill="#E5E5E5"
            />
          </g>
        </g>
        <defs>
          <filter
            id="filter0_b_25_6344"
            x="792"
            y="474"
            width="140"
            height="198"
            filterUnits="userSpaceOnUse"
            colorInterpolationFilters="sRGB"
          >
            <feFlood floodOpacity="0" result="BackgroundImageFix" />
            <feGaussianBlur in="BackgroundImage" stdDeviation="2" />
            <feComposite
              in2="SourceAlpha"
              operator="in"
              result="effect1_backgroundBlur_25_6344"
            />
            <feBlend
              mode="normal"
              in="SourceGraphic"
              in2="effect1_backgroundBlur_25_6344"
              result="shape"
            />
          </filter>
          <filter
            id="filter1_b_25_6344"
            x="953"
            y="474"
            width="140"
            height="198"
            filterUnits="userSpaceOnUse"
            colorInterpolationFilters="sRGB"
          >
            <feFlood floodOpacity="0" result="BackgroundImageFix" />
            <feGaussianBlur in="BackgroundImage" stdDeviation="2" />
            <feComposite
              in2="SourceAlpha"
              operator="in"
              result="effect1_backgroundBlur_25_6344"
            />
            <feBlend
              mode="normal"
              in="SourceGraphic"
              in2="effect1_backgroundBlur_25_6344"
              result="shape"
            />
          </filter>
          <filter
            id="filter2_b_25_6344"
            x="1115"
            y="474"
            width="140"
            height="198"
            filterUnits="userSpaceOnUse"
            colorInterpolationFilters="sRGB"
          >
            <feFlood floodOpacity="0" result="BackgroundImageFix" />
            <feGaussianBlur in="BackgroundImage" stdDeviation="2" />
            <feComposite
              in2="SourceAlpha"
              operator="in"
              result="effect1_backgroundBlur_25_6344"
            />
            <feBlend
              mode="normal"
              in="SourceGraphic"
              in2="effect1_backgroundBlur_25_6344"
              result="shape"
            />
          </filter>
          <filter
            id="filter3_b_25_6344"
            x="176"
            y="474"
            width="403"
            height="430"
            filterUnits="userSpaceOnUse"
            colorInterpolationFilters="sRGB"
          >
            <feFlood floodOpacity="0" result="BackgroundImageFix" />
            <feGaussianBlur in="BackgroundImage" stdDeviation="2" />
            <feComposite
              in2="SourceAlpha"
              operator="in"
              result="effect1_backgroundBlur_25_6344"
            />
            <feBlend
              mode="normal"
              in="SourceGraphic"
              in2="effect1_backgroundBlur_25_6344"
              result="shape"
            />
          </filter>
        </defs>
      </svg>
    </>
  );
}

export default LoaderOne;
